### ISSUE TITLE
Wrong include path order causes build error: modules/xobjdetect/src/waldboost.hpp:53:7: error: redefinition of ‘class cv::xobjdetect::WaldBoost’

### ISSUE THREAD

**Issue by devurandom** [Itseez/opencv_contrib#675]
### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Linux (Gentoo)
- Compiler & CMake: GCC 5.3.0 & CMake 3.5.2

### In which part of the OpenCV library you got the issue?

Build system

### Expected behaviour

xobjdetect compiles fine. In particular: source include paths are ordered before system include paths.

### Actual behaviour

The include path order is broken and `/usr/include` appears before `modules/xobjdetect/include`, causing following build error:
```
In file included from /var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build/modules/xobjdetect/precomp.hpp:77:0:
/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv_contrib-3.1.0/modules/xobjdetect/src/waldboost.hpp:53:7: error: redefinition of ‘class cv::xobjdetect::WaldBoost’
 class WaldBoost {
       ^
In file included from /var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build/modules/xobjdetect/precomp.hpp:48:0:
/usr/include/opencv2/xobjdetect.hpp:136:18: error: previous definition of ‘class cv::xobjdetect::WaldBoost’
 class CV_EXPORTS WaldBoost : public Algorithm
                  ^
In file included from /var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build/modules/xobjdetect/precomp.hpp:78:0:
/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv_contrib-3.1.0/modules/xobjdetect/src/wbdetector.hpp:56:42: error: expected class-name before ‘{’ token
 class WBDetectorImpl : public WBDetector {
                                          ^
/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv_contrib-3.1.0/modules/xobjdetect/src/wbdetector.hpp:71:15: error: cannot declare field ‘cv::xobjdetect::WBDetectorImpl::boost_’ to be of abstract type ‘cv::xobjdetect::WaldBoost’
     WaldBoost boost_;
               ^
In file included from /var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build/modules/xobjdetect/precomp.hpp:48:0:
/usr/include/opencv2/xobjdetect.hpp:136:18: note:   because the following virtual functions are pure within ‘cv::xobjdetect::WaldBoost’:
 class CV_EXPORTS WaldBoost : public Algorithm
                  ^
/usr/include/opencv2/xobjdetect.hpp:146:30: note:       virtual std::vector<int> cv::xobjdetect::WaldBoost::train(cv::Mat&, const cv::Mat&, bool)
     virtual std::vector<int> train(Mat& data,
                              ^
/usr/include/opencv2/xobjdetect.hpp:154:19: note:       virtual float cv::xobjdetect::WaldBoost::predict(const cv::Ptr<cv::xobjdetect::FeatureEvaluator>&) const
     virtual float predict(
                   ^
make[2]: Leaving directory '/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build'
```

### Additional description

The system header `/usr/include/opencv2/xobjdetect.hpp` is being included instead of the header in the source tree at `opencv_contrib-3.1.0/modules/xobjdetect/include/opencv2/xobjdetect.hpp`.

The reason for that is a wrong order of include directories in the call to GCC:
`cd /var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build/modules/xobjdetect && /usr/bin/x86_64-pc-linux-gnu-g++ -fPIC "-D__OPENCV_BUILD=1" "-DCVAPI_EXPORTS" -isystem"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build" -isystem"/usr/include" -isystem"/usr/include/eigen3" -isystem"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build" -isystem"/usr/include" -isystem"/usr/include/eigen3" -isystem"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv_contrib-3.1.0/modules/xobjdetect/include" -isystem"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv_contrib-3.1.0/modules/xobjdetect/src" -isystem"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build/modules/xobjdetect" -I"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0/modules/core/include" -I"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0/modules/imgproc/include" -I"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0/modules/ml/include" -I"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0/modules/imgcodecs/include" -I"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0/modules/videoio/include" -I"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0/modules/highgui/include" -I"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0/modules/objdetect/include" -pipe -O2 -march=bdver3 -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -DCVAPI_EXPORTS -x c++-header -o /var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build/modules/xobjdetect/precomp.hpp.gch/opencv_xobjdetect_Gentoo.gch /var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv-3.1.0_build/modules/xobjdetect/precomp.hpp`

Here, `-isystem"/usr/include"` appears (several times) before `-isystem"/var/tmp/portage/media-libs/opencv-3.1.0-r2/work/opencv_contrib-3.1.0/modules/xobjdetect/include"`.

All the module's local directories are being added via `target_include_directories()`, called in `ocv_target_include_directories()`, when `ocv_define_module()` is being called. However, when actually building, `-isystem".../opencv-3.1.0_build" -isystem"/usr/include" -isystem"/usr/include/eigen3" -isystem".../work/opencv-3.1.0_build" -isystem"/usr/include" -isystem"/usr/include/eigen3"` suddenly appears out of thin air before them on the command line. I am unable to figure out how that command line is actually being composed.

You can find all the details in https://bugs.gentoo.org/show_bug.cgi?id=575690

**Comment by alalek** [comment]
Fixed in master branch: https://github.com/Itseez/opencv/pull/6410

**Comment by devurandom** [comment]
> Fixed in master branch: Itseez/opencv#6410

Sadly the issue still exists after applying the patch: [build.log.zip](https://github.com/Itseez/opencv_contrib/files/275899/build.log.zip)

**Comment by alalek** [comment]
Could you try to disable PCH: `cmake -DENABLE_PRECOMPILED_HEADERS=OFF ...`?
Also please attach `CMakeVars.txt` file from build directory.

**Comment by devurandom** [comment]
> Also please attach CMakeVars.txt file from build directory.

There is no such file, but I can give you `CMakeCache.txt`, which hopefully contains the information you need: [CMakeCache.txt.zip](https://github.com/Itseez/opencv_contrib/files/275937/CMakeCache.txt.zip) (from the build run which included 9393a0c5bb942215f15ccb0c940c23b284f19b15 but was still broken)

**Comment by devurandom** [comment]
And again for the run with `PRECOMPILED_HEADERS` disabled: [build.log.and.CMakeCache.txt.zip](https://github.com/Itseez/opencv_contrib/files/275975/build.log.and.CMakeCache.txt.zip)

**Comment by alalek** [comment]
I checked your paths, which contain dots `.`, but there is still no problem for CMake `MATCHES` condition and patched checks work as expected.

Looks like build is succeed with disabled PCH support.

**Comment by devurandom** [comment]
> Looks like build is succeed with disabled PCH support.

Yes, it did. Sorry, forgot to mention that.
